'use client';
import { useCallback, useEffect, useState } from 'react';
import { api, OrgAccount } from '../../../lib/api';
import { getStoredOrgId } from '../../../lib/auth';

const card:React.CSSProperties={background:'#111118',border:'1px solid #1e1e2a',borderRadius:10,padding:'1.25rem',marginBottom:'1rem'};
const input:React.CSSProperties={width:'100%',padding:'.6rem .8rem',borderRadius:7,border:'1px solid #252532',background:'#0d0d14',color:'#f1f5f9'};
const label:React.CSSProperties={display:'block',fontSize:'.78rem',color:'#94a3b8',marginBottom:'.3rem'};
const button:React.CSSProperties={padding:'.55rem 1rem',border:0,borderRadius:7,background:'#6366f1',color:'white',fontWeight:600,cursor:'pointer'};

export default function AccountsPage(){
 const orgId=getStoredOrgId();
 const [accounts,setAccounts]=useState<OrgAccount[]>([]);const [currentUserId,setCurrentUserId]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [success,setSuccess]=useState('');const [deleting,setDeleting]=useState('');
 const [name,setName]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [confirmPassword,setConfirmPassword]=useState('');const [role,setRole]=useState<'operator'|'viewer'>('operator');const [saving,setSaving]=useState(false);
 const load=useCallback(async()=>{if(!orgId)return;setLoading(true);try{const [rows,profile]=await Promise.all([api.get<OrgAccount[]>(`/api/orgs/${orgId}/accounts`),api.get<{userId:string}>('/api/auth/me')]);setAccounts(rows);setCurrentUserId(profile.userId);setError('');}catch(e){setError(e instanceof Error?e.message:'Could not load accounts');}finally{setLoading(false);}},[orgId]);
 useEffect(()=>{void load();},[load]);
 async function create(e:React.FormEvent){e.preventDefault();setError('');setSuccess('');if(password.length<12){setError('Password must be at least 12 characters.');return;}if(password!==confirmPassword){setError('Passwords do not match.');return;}if(!orgId)return;setSaving(true);try{const created=await api.post<OrgAccount>(`/api/orgs/${orgId}/accounts`,{name,email,password,role});setAccounts(current=>[...current,created]);setName('');setEmail('');setPassword('');setConfirmPassword('');setSuccess(`${created.email} created as ${created.role}. You may now use this login in the Discord bot configuration.`);}catch(e){setError(e instanceof Error?e.message:'Could not create account');}finally{setSaving(false);}}
 async function remove(account:OrgAccount){if(!orgId||account.id===currentUserId)return;const warning=`Delete organization account "${account.email}"?\n\nThis immediately removes its Mastermind access and disables sign-in if this is its only organization. Past job and audit attribution will be retained.`;if(!confirm(warning))return;setDeleting(account.id);setError('');setSuccess('');try{await api.delete(`/api/orgs/${orgId}/accounts/${account.id}`);setAccounts(current=>current.filter(row=>row.id!==account.id));setSuccess(`${account.email} was removed from this organization.`);}catch(e){setError(e instanceof Error?e.message:'Could not delete account');}finally{setDeleting('');}}
 return <div><div style={{marginBottom:'1.5rem'}}><h1 style={{margin:0,fontSize:'1.5rem'}}>Accounts</h1><p style={{color:'#64748b',margin:'.3rem 0 0'}}>Create and view people or service accounts in this Mastermind organization.</p></div>
  <div style={card}><h2 style={{marginTop:0,fontSize:'1rem'}}>Create account</h2><p style={{color:'#94a3b8',fontSize:'.82rem'}}>Use <strong>Operator</strong> for the Discord bot or staff who need server controls. Use <strong>Viewer</strong> for read-only access. Only organization administrators can use this page.</p>
   <form onSubmit={create} style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:12}}>
    <div><label style={label}>Display name</label><input style={input} value={name} onChange={e=>setName(e.target.value)} placeholder="Discord Bot" /></div>
    <div><label style={label}>Email used to sign in</label><input style={input} type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="discord-bot@example.com" required /></div>
    <div><label style={label}>Password (at least 12 characters)</label><input style={input} type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={12} required /></div>
    <div><label style={label}>Confirm password</label><input style={input} type="password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} minLength={12} required /></div>
    <div><label style={label}>Access level</label><select style={input} value={role} onChange={e=>setRole(e.target.value as 'operator'|'viewer')}><option value="operator">Operator — can control servers</option><option value="viewer">Viewer — read only</option></select></div>
    <div style={{alignSelf:'end'}}><button style={button} disabled={saving}>{saving?'Creating…':'Create account'}</button></div>
   </form>{error&&<p style={{color:'#f87171',fontSize:'.82rem'}}>{error}</p>}{success&&<p style={{color:'#4ade80',fontSize:'.82rem'}}>{success}</p>}
  </div>
  <div style={card}><h2 style={{marginTop:0,fontSize:'1rem'}}>Organization accounts</h2><p style={{color:'#64748b',fontSize:'.78rem'}}>Deleting removes organization access but keeps names on historical jobs and audit records. You cannot delete yourself or the last administrator.</p>{loading?<p style={{color:'#64748b'}}>Loading…</p>:accounts.length===0?<p style={{color:'#64748b'}}>No accounts found.</p>:<div style={{overflowX:'auto'}}><table><thead><tr>{['Name','Email','Access','Created','Actions'].map(x=><th key={x} style={{textAlign:'left',padding:'.65rem',color:'#64748b',fontSize:'.75rem',borderBottom:'1px solid #252532'}}>{x}</th>)}</tr></thead><tbody>{accounts.map(account=><tr key={account.id}><td style={{padding:'.7rem',borderBottom:'1px solid #1e1e2a'}}>{account.name||'—'}{account.id===currentUserId&&<small style={{color:'#818cf8',marginLeft:6}}>(you)</small>}</td><td style={{padding:'.7rem',borderBottom:'1px solid #1e1e2a'}}>{account.email}</td><td style={{padding:'.7rem',borderBottom:'1px solid #1e1e2a',textTransform:'capitalize'}}>{account.role}</td><td style={{padding:'.7rem',borderBottom:'1px solid #1e1e2a',color:'#94a3b8'}}>{new Date(account.createdAt).toLocaleString()}</td><td style={{padding:'.7rem',borderBottom:'1px solid #1e1e2a'}}><button type="button" disabled={account.id===currentUserId||Boolean(deleting)} title={account.id===currentUserId?'You cannot delete your own account':'Remove this account from the organization'} onClick={()=>void remove(account)} style={{padding:'.4rem .65rem',border:'1px solid #7f1d1d',borderRadius:6,background:account.id===currentUserId?'#334155':'#991b1b',color:'white',cursor:account.id===currentUserId?'not-allowed':'pointer',opacity:account.id===currentUserId ? .55 : 1}}>{deleting===account.id?'Deleting…':'Delete'}</button></td></tr>)}</tbody></table></div>}</div>
 </div>;
}
