'use client';
import { useEffect,useMemo,useState } from 'react';
import { MapContainer,TileLayer,Marker,Popup,LayersControl,LayerGroup,useMap } from 'react-leaflet';
import L from 'leaflet';
import { PortalFrame } from '../PortalFrame';
type Entity={id:string|number;name:string;position:{x:number;y:number;z:number}};
type Config={enabled:boolean;maxZoom?:number;mapSize:{x:number;y:number;z:number}};
type Profile={name:string;steamId:string;serverName:string;online:boolean;auth?:string};
const icon=(color:string,label?:string)=>L.divIcon({className:'',html:`<div style="display:flex;align-items:center;gap:5px;white-space:nowrap"><span style="display:block;width:14px;height:14px;border-radius:50%;background:${color};border:2px solid white;box-shadow:0 1px 5px #000"></span>${label?`<strong style="color:white;text-shadow:0 1px 4px #000;font:12px system-ui">${label.replace(/[&<>"']/g,'')}</strong>`:''}</div>`,iconSize:[18,18],iconAnchor:[9,9]});
function Fit({bounds}:{bounds:L.LatLngBoundsExpression}){const map=useMap();useEffect(()=>{map.fitBounds(bounds,{padding:[12,12]});},[map,bounds]);return null;}
export default function PlayerMapClient(){
 const [profile,setProfile]=useState<Profile|null>(null),[config,setConfig]=useState<Config|null>(null),[players,setPlayers]=useState<Entity[]>([]),[animals,setAnimals]=useState<Entity[]>([]),[hostiles,setHostiles]=useState<Entity[]>([]),[error,setError]=useState(''),[feedError,setFeedError]=useState('');
 useEffect(()=>{fetch('/api/player-auth/me',{cache:'no-store'}).then(async r=>{if(r.ok){const next=await r.json();if(next.auth!=='name')setProfile(next);}});},[]);
 useEffect(()=>{let active=true;const get=async(path:string)=>{const r=await fetch(`/api/player-map/${path}`,{cache:'no-store'}),body=await r.json();if(!r.ok)throw new Error(body.message||`Map error ${r.status}`);return body.data??body;};get('api/map/config').then(v=>active&&setConfig(v)).catch(e=>active&&setError(e.message));const update=()=>get('entities-live').then(v=>{if(!active)return;setPlayers(v.players??[]);setAnimals(v.animals??[]);setHostiles(v.hostiles??[]);const errors=v.errors||{};setFeedError([errors.players,errors.hostiles,errors.animals].filter(Boolean).join(' · ')||'');}).catch(e=>active&&setFeedError(e.message));update();const timer=setInterval(update,10000);return()=>{active=false;clearInterval(timer);};},[]);
 const mapSize=config?.mapSize||{x:10240,y:255,z:10240};
 // Polling entities re-renders this component. Stable bounds prevent Fit from
 // running again and unexpectedly zooming the map out.
 const bounds=useMemo(()=>L.latLngBounds([-mapSize.x/2,-mapSize.z/2],[mapSize.x/2,mapSize.z/2]),[mapSize.x,mapSize.z]);
 const crs=useMemo(()=>{const divisor=2**(config?.maxZoom??4);return L.extend({},L.CRS.Simple,{projection:{project:(p:L.LatLng)=>new L.Point(p.lat/divisor,p.lng/divisor),unproject:(p:L.Point)=>new L.LatLng(p.x*divisor,p.y*divisor),bounds:L.bounds([-Infinity,-Infinity],[Infinity,Infinity])},transformation:new L.Transformation(1,0,-1,0),scale:(zoom:number)=>2**zoom}) as L.CRS;},[config?.maxZoom]);
 if(error)return <PortalFrame profile={profile} wide><div style={alertStyle}>{error}</div></PortalFrame>;if(!config)return <PortalFrame profile={profile} wide><p style={{color:'#94a3b8'}}>Connecting to live map…</p></PortalFrame>;
 return <PortalFrame profile={profile} wide><div style={{display:'flex',gap:13,flexWrap:'wrap',fontSize:13,marginBottom:8}}>{profile?<span style={{color:'#60a5fa'}}>Players {players.length} · Steam verified</span>:<a href="/player" style={{color:'#fbbf24'}}>Players hidden · sign in through Steam</a>}<span style={{color:'#4ade80'}}>Animals {animals.length}</span><span style={{color:'#f87171'}}>Zombies/hostiles {hostiles.length}</span>{feedError&&<span style={{color:'#fbbf24'}}>{feedError}</span>}</div><div style={{height:'calc(100vh - 165px)',minHeight:480,border:'1px solid #292936',borderRadius:10,overflow:'hidden'}}><MapContainer crs={crs} center={[0,0]} zoom={1} minZoom={-1} maxZoom={5} maxBounds={bounds.pad(.12)} fadeAnimation={false} style={{height:'100%',width:'100%',background:'#111827'}}><Fit bounds={bounds}/><TileLayer url="/api/player-map/map/{z}/{x}/{y}.png" noWrap bounds={bounds} tileSize={128} minZoom={-1} minNativeZoom={0} maxNativeZoom={config.maxZoom??4} keepBuffer={16} updateInterval={50} updateWhenIdle={false} updateWhenZooming/><LayersControl position="topright">{profile&&<LayersControl.Overlay checked name="Players"><LayerGroup>{players.map(e=><Marker key={e.id} position={[e.position.x,e.position.z]} icon={icon('#3b82f6',e.name)}><Popup><strong>{e.name}</strong><br/>{Math.round(e.position.x)}, {Math.round(e.position.z)}</Popup></Marker>)}</LayerGroup></LayersControl.Overlay>}<LayersControl.Overlay checked name="Animals"><LayerGroup>{animals.map(e=><Marker key={e.id} position={[e.position.x,e.position.z]} icon={icon('#22c55e')}><Popup>{e.name}</Popup></Marker>)}</LayerGroup></LayersControl.Overlay><LayersControl.Overlay checked name="Zombies & hostiles"><LayerGroup>{hostiles.map(e=><Marker key={e.id} position={[e.position.x,e.position.z]} icon={icon('#ef4444')}><Popup>{e.name}</Popup></Marker>)}</LayerGroup></LayersControl.Overlay></LayersControl></MapContainer></div></PortalFrame>;
}
const alertStyle:React.CSSProperties={padding:'1rem',background:'#3f1d25',color:'#fca5a5',borderRadius:8};
