'use client';
import { useCallback,useEffect,useState } from 'react';
import { api,Job,ServerInstance } from '../../../lib/api';
import { getStoredOrgId } from '../../../lib/auth';

type Credit={name:string;upstreamAuthor:string;upstreamRepository:string;upstreamCommit:string;license:string};
type Profile={path:string;name:string;playerName?:string;world:string;save:string;sizeBytes:number;modifiedAt:string};
type ProfileResult={data?:{profiles?:Profile[];profile?:Profile;contentBase64?:string};errorMessage?:string};
const card:React.CSSProperties={background:'#111118',border:'1px solid #1e1e2a',borderRadius:10,padding:'1.25rem',marginBottom:'1rem'};
const button:React.CSSProperties={padding:'.55rem .8rem',border:0,borderRadius:7,background:'#4f46e5',color:'white',fontWeight:600,cursor:'pointer'};

export default function ProfileEditorPage(){
 const orgId=getStoredOrgId();const [credit,setCredit]=useState<Credit|null>(null);const [servers,setServers]=useState<ServerInstance[]>([]);const [serverId,setServerId]=useState('');const [profiles,setProfiles]=useState<Profile[]>([]);const [open,setOpen]=useState(false);const [frameSrc,setFrameSrc]=useState('/api/profile-editor-tool/index.php?lang=en');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [frameKey,setFrameKey]=useState(0);
 useEffect(()=>{if(!orgId)return;void api.get<Credit>(`/api/orgs/${orgId}/integrations/profile-editor`).then(setCredit).catch(()=>undefined);void api.get<ServerInstance[]>(`/api/orgs/${orgId}/server-instances`).then(rows=>{const found=rows.filter(row=>row.gameType==='7dtd');setServers(found);if(found[0])setServerId(found[0].id);}).catch(e=>setError(e instanceof Error?e.message:'Could not load servers'));},[orgId]);
 const waitForJob=useCallback(async(runId:string)=>{for(let i=0;i<60;i++){await new Promise(resolve=>setTimeout(resolve,1000));const jobs=await api.get<Job[]>(`/api/orgs/${orgId}/jobs?limit=100&serverInstanceId=${encodeURIComponent(serverId)}`);const job=jobs.find(row=>row.latestRun?.id===runId);if(job?.latestRun?.status==='failed'){const result=job.latestRun.result as ProfileResult|undefined;throw new Error(result?.errorMessage||'Profile operation failed');}if(job?.latestRun?.status==='success')return(job.latestRun.result||{})as ProfileResult;}throw new Error('Profile operation timed out');},[orgId,serverId]);
 const run=useCallback(async(type:string,payload:Record<string,unknown>={})=>{if(!orgId||!serverId)throw new Error('Select a server first');const queued=await api.post<{jobRunId:string}>(`/api/orgs/${orgId}/jobs`,{serverInstanceId:serverId,type,payload});return waitForJob(queued.jobRunId);},[orgId,serverId,waitForJob]);
 const authorize=useCallback(async(target?:Profile)=>{const token=localStorage.getItem('mm_token');if(!token)throw new Error('Sign in again before opening the editor.');const response=await fetch('/api/profile-editor-session',{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify(target?{orgId,serverId,path:target.path}:{}),credentials:'same-origin'});if(!response.ok)throw new Error('Could not authorize the Profile Editor session');},[orgId,serverId]);
 const refresh=useCallback(async()=>{if(!serverId)return;setBusy(true);setError('');try{const result=await run('PROFILE_LIST');setProfiles(result.data?.profiles||[]);}catch(e){setError(e instanceof Error?e.message:'Could not read player profiles');}finally{setBusy(false);}},[serverId,run]);
 useEffect(()=>{if(serverId)void refresh();},[serverId,refresh]);
 async function launch(){setBusy(true);setError('');setMessage('');try{await authorize();setFrameSrc('/api/profile-editor-tool/upload.php?reset=1&lang=en');setOpen(true);setFrameKey(value=>value+1);}catch(e){setError(e instanceof Error?e.message:'Could not open Profile Editor');}finally{setBusy(false);}}
 async function edit(profile:Profile){setBusy(true);setError('');setMessage(`Copying ${profile.name} from the server…`);try{await authorize(profile);const result=await run('PROFILE_READ',{path:profile.path});const encoded=result.data?.contentBase64;if(!encoded)throw new Error('The agent returned an empty profile copy');const bytes=Uint8Array.from(atob(encoded),value=>value.charCodeAt(0));const form=new FormData();form.append('ttpFile',new Blob([bytes],{type:'application/octet-stream'}),profile.name);const uploaded=await fetch('/api/profile-editor-tool/upload.php?lang=en',{method:'POST',body:form,credentials:'same-origin'});if(!uploaded.ok)throw new Error(`Editor rejected the profile (${uploaded.status})`);setFrameSrc('/api/profile-editor-tool/upload.php?lang=en');setOpen(true);setFrameKey(value=>value+1);setMessage(`Loaded ${profile.name}. Downloading your edited result will stage it for the next server restart.`);}catch(e){setError(e instanceof Error?e.message:'Could not load profile');setMessage('');}finally{setBusy(false);}}
 return <div><div style={{marginBottom:'1.5rem'}}><h1 style={{margin:0,fontSize:'1.5rem'}}>7D2D Profile Editor</h1><p style={{color:'#64748b',margin:'.3rem 0 0'}}>Load a copy of an existing server profile or upload one manually.</p></div>
  <div style={{...card,borderColor:'#92400e',background:'rgba(120,53,15,.12)'}}><h2 style={{marginTop:0,fontSize:'1rem',color:'#fbbf24'}}>Staged live editing</h2><p style={{color:'#cbd5e1',fontSize:'.84rem',lineHeight:1.6,marginBottom:0}}>Downloading an edited server profile queues it for that exact player. The live file stays unchanged until the next Mastermind-managed start or restart. With 7DTD stopped, the agent backs up the current profile and installs the queued version atomically before starting the server.</p></div>
  <div style={card}><div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'center',flexWrap:'wrap'}}><div><h2 style={{margin:'0 0 .25rem',fontSize:'1rem'}}>Profiles on server</h2><small style={{color:'#64748b'}}>Player names are matched from each save&apos;s <code>players.xml</code> when available.</small></div><div style={{display:'flex',gap:8}}><select value={serverId} onChange={e=>setServerId(e.target.value)} style={{background:'#0d0d14',color:'#e2e8f0',border:'1px solid #252532',borderRadius:6,padding:'.5rem'}}>{servers.map(server=><option key={server.id} value={server.id}>{server.name}</option>)}</select><button disabled={busy||!serverId} onClick={()=>void refresh()} style={button}>Refresh</button></div></div>{error&&<p style={{color:'#f87171',fontSize:'.82rem'}}>{error}</p>}{message&&<p style={{color:'#4ade80',fontSize:'.82rem'}}>{message}</p>}<div style={{overflowX:'auto',marginTop:12}}><table style={{width:'100%',minWidth:820,borderCollapse:'collapse'}}><thead><tr>{['Player','Profile','World / Save','Modified','Size','Action'].map(label=><th key={label} style={{textAlign:'left',padding:'.6rem',fontSize:'.72rem',color:'#64748b',borderBottom:'1px solid #252532'}}>{label}</th>)}</tr></thead><tbody>{profiles.length===0?<tr><td colSpan={6} style={{padding:'.8rem',color:'#64748b'}}>{busy?'Reading profiles…':'No player profiles found.'}</td></tr>:profiles.map(profile=><tr key={profile.path}><td style={{...td,fontWeight:600,color:profile.playerName?'#f1f5f9':'#64748b'}}>{profile.playerName||'Unknown'}</td><td style={td}><code>{profile.name}</code></td><td style={td}>{profile.world} / {profile.save}</td><td style={td}>{new Date(profile.modifiedAt).toLocaleString()}</td><td style={td}>{formatBytes(profile.sizeBytes)}</td><td style={td}><button disabled={busy} onClick={()=>void edit(profile)} style={button}>Edit copy</button></td></tr>)}</tbody></table></div></div>
  <div style={card}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><h2 style={{margin:'0 0 .3rem',fontSize:'1rem'}}>Editor</h2><p style={{color:'#94a3b8',fontSize:'.8rem',margin:0}}>Use “Edit copy” above for a server profile, or open the editor for manual upload.</p></div><button disabled={busy} onClick={()=>void launch()} style={button}>{open?'Reset / manual upload':'Open for manual upload'}</button></div>{open&&<iframe key={frameKey} title="7D2D Profile Editor" src={frameSrc} style={{display:'block',width:'100%',minHeight:'75vh',border:'1px solid #334155',borderRadius:8,marginTop:14,background:'#f8f9fa'}} sandbox="allow-forms allow-scripts allow-downloads allow-same-origin" />}</div>
  <div style={card}><h2 style={{marginTop:0,fontSize:'1rem'}}>Credit and license</h2><p style={{color:'#cbd5e1',fontSize:'.84rem'}}>Integrated from <a href={credit?.upstreamRepository||'https://github.com/RussDev7/7D2DProfileEditor'} target="_blank" rel="noreferrer" style={{color:'#818cf8'}}>{credit?.name||'7 Days to Die TTP Profile Editor'}</a> by <strong>{credit?.upstreamAuthor||'RussDev7 / DannyRuss'}</strong>, licensed under {credit?.license||'GNU GPL v3'}.</p><p style={{color:'#64748b',fontSize:'.76rem'}}>Pinned revision: <code>{credit?.upstreamCommit||'270f998adf70f3724afd93ba0e08569e3ba78c95'}</code>. Mastermind does not claim authorship of the editor or its profile-format research.</p></div>
 </div>;
}
const td:React.CSSProperties={padding:'.65rem',fontSize:'.8rem',color:'#cbd5e1',borderBottom:'1px solid #1e1e2a'};
function formatBytes(value:number){if(value<1024)return `${value} B`;if(value<1048576)return `${(value/1024).toFixed(1)} KiB`;return `${(value/1048576).toFixed(1)} MiB`;}
