'use client';
import { useCallback,useEffect,useState } from 'react';
import { api,Job,ModRecord,ServerInstance } from '../../../lib/api';
import { getStoredOrgId } from '../../../lib/auth';
type View='active'|'quarantined';type JobResult={data?:{mods?:ModRecord[]};errorMessage?:string};
const th={textAlign:'left' as const,padding:'.75rem',color:'#64748b',fontSize:'.72rem',borderBottom:'1px solid #1e1e2a'};const td={padding:'.75rem',color:'#cbd5e1',borderBottom:'1px solid #1e1e2a'};
export default function ModsPage(){
 const orgId=getStoredOrgId();const [server,setServer]=useState<ServerInstance|null>(null);const [mods,setMods]=useState<ModRecord[]>([]);const [view,setView]=useState<View>('active');const [selected,setSelected]=useState<Set<string>>(new Set());const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 const waitForJob=useCallback(async(runId:string)=>{for(let i=0;i<30;i++){await new Promise(r=>setTimeout(r,1000));const jobs=await api.get<Job[]>(`/api/orgs/${orgId}/jobs?limit=100`);const job=jobs.find(j=>j.latestRun?.id===runId);if(job?.latestRun?.status==='failed')throw new Error((job.latestRun.result as JobResult)?.errorMessage||'Agent job failed');if(job?.latestRun?.status==='success')return(job.latestRun.result||{})as JobResult;}throw new Error('Agent job timed out');},[orgId]);
 const load=useCallback(async(target?:ServerInstance,targetView:View=view)=>{if(!orgId)return;setBusy(true);setMessage('');try{let selectedServer=target||server;if(!selectedServer){const servers=await api.get<ServerInstance[]>(`/api/orgs/${orgId}/server-instances`);selectedServer=servers.find(s=>s.gameType==='7dtd')||null;setServer(selectedServer);}if(!selectedServer)throw new Error('No 7DTD server found');const queued=await api.post<{jobRunId:string}>(`/api/orgs/${orgId}/jobs`,{serverInstanceId:selectedServer.id,type:targetView==='active'?'MOD_LIST':'MOD_QUARANTINE_LIST',payload:{}});const result=await waitForJob(queued.jobRunId);setMods(result.data?.mods||[]);setSelected(new Set());}catch(e){setMessage(e instanceof Error?e.message:'Failed to load mods');}finally{setBusy(false);}},[orgId,server,view,waitForJob]);
 useEffect(()=>{void load();},[]);
 async function action(mod:ModRecord,type:'MOD_QUARANTINE'|'MOD_DELETE'|'MOD_RESTORE'){if(!orgId||!server)return;const prompt=type==='MOD_DELETE'?`Permanently delete "${mod.folder}"? This cannot be undone.`:type==='MOD_RESTORE'?`Restore "${mod.folder}" to Mods? It will load after restart.`:`Quarantine "${mod.folder}"? It will stop loading after restart.`;if(!confirm(prompt))return;setBusy(true);setMessage('');try{const queued=await api.post<{jobRunId:string}>(`/api/orgs/${orgId}/jobs`,{serverInstanceId:server.id,type,payload:{folder:mod.folder}});await waitForJob(queued.jobRunId);const verb=type==='MOD_DELETE'?'Deleted':type==='MOD_RESTORE'?'Restored':'Quarantined';setMessage(`${verb} ${mod.name}. Restart server to apply.`);await load(server,view);}catch(e){setMessage(e instanceof Error?e.message:'Mod action failed');}finally{setBusy(false);}}
 async function bulkAction(type:'MOD_QUARANTINE'|'MOD_DELETE'|'MOD_RESTORE'){if(!orgId||!server||selected.size===0)return;const chosen=mods.filter(m=>selected.has(m.folder));const verb=type==='MOD_DELETE'?'permanently delete':type==='MOD_RESTORE'?'restore':'quarantine';const warning=type==='MOD_DELETE'?`Permanently delete ${chosen.length} selected mods? This cannot be undone.`:`${verb[0].toUpperCase()+verb.slice(1)} ${chosen.length} selected mods?`;if(!confirm(warning))return;setBusy(true);setMessage(`Queuing ${chosen.length} mod actions…`);try{const queued=await Promise.all(chosen.map(mod=>api.post<{jobRunId:string}>(`/api/orgs/${orgId}/jobs`,{serverInstanceId:server.id,type,payload:{folder:mod.folder}})));const results=await Promise.allSettled(queued.map(job=>waitForJob(job.jobRunId)));const failed=results.filter(result=>result.status==='rejected').length;await load(server,view);setMessage(failed?`Completed ${chosen.length-failed} of ${chosen.length}; ${failed} failed. Check Jobs for details.`:`${verb[0].toUpperCase()+verb.slice(1)}d ${chosen.length} mods. Restart server to apply.`);}catch(e){setMessage(e instanceof Error?e.message:'Bulk mod action failed');}finally{setBusy(false);}}
 function switchView(next:View){setView(next);setSelected(new Set());void load(server||undefined,next);}function toggle(folder:string){setSelected(current=>{const next=new Set(current);if(next.has(folder))next.delete(folder);else next.add(folder);return next;});}function toggleAll(){setSelected(selected.size===mods.length?new Set():new Set(mods.map(mod=>mod.folder)));}
 return <div style={{maxWidth:'100%',minWidth:0}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'start',gap:16,marginBottom:'1rem'}}><div><h1 style={{margin:'0 0 .25rem',color:'#f1f5f9',fontSize:'1.5rem'}}>Mods</h1><p style={{color:'#64748b',margin:0}}>Manage active and quarantined server-side mods. Metadata comes from ModInfo.xml.</p></div><button disabled={busy} onClick={()=>load(server||undefined,view)} style={button('#4f46e5')}>{busy?'Working…':'Refresh'}</button></div>
 <div style={{display:'flex',gap:6,borderBottom:'1px solid #1e1e2a',marginBottom:'1rem'}}>{(['active','quarantined']as const).map(key=><button key={key} onClick={()=>switchView(key)} style={{background:'transparent',border:0,borderBottom:view===key?'2px solid #6366f1':'2px solid transparent',color:view===key?'#f1f5f9':'#64748b',padding:'.65rem .9rem',cursor:'pointer',textTransform:'capitalize'}}>{key==='active'?'Active Mods':'Quarantined Mods'}{view===key?` (${mods.length})`:''}</button>)}</div>{selected.size>0&&<div style={{display:'flex',alignItems:'center',gap:8,flexWrap:'wrap',background:'#111118',border:'1px solid #252532',borderRadius:8,padding:'.7rem .85rem',marginBottom:'1rem'}}><strong style={{color:'#e2e8f0',fontSize:'.82rem'}}>{selected.size} selected</strong>{view==='active'?<><button disabled={busy} onClick={()=>bulkAction('MOD_QUARANTINE')} style={button('#b45309')}>Quarantine selected</button><button disabled={busy} onClick={()=>bulkAction('MOD_DELETE')} style={button('#991b1b')}>Delete selected</button></>:<button disabled={busy} onClick={()=>bulkAction('MOD_RESTORE')} style={button('#15803d')}>Restore selected</button>}<button disabled={busy} onClick={()=>setSelected(new Set())} style={button('#334155')}>Clear</button></div>}
 {message&&<div style={{color:/^(Deleted|Restored|Quarantined|Completed)/.test(message)?'#4ade80':'#fbbf24',marginBottom:12}}>{message}</div>}<div style={{background:'#111118',border:'1px solid #1e1e2a',borderRadius:9,overflowX:'auto',maxWidth:'100%'}}><table style={{width:'100%',minWidth:860,tableLayout:'fixed',borderCollapse:'collapse'}}><colgroup><col style={{width:44}}/><col style={{width:'17%'}}/><col style={{width:'17%'}}/><col style={{width:'8%'}}/><col style={{width:'13%'}}/><col style={{width:'22%'}}/><col style={{width:'18%'}}/></colgroup><thead><tr><th style={th}><input type="checkbox" aria-label="Select all mods" checked={mods.length>0&&selected.size===mods.length} onChange={toggleAll}/></th>{['Mod','Folder','Version','Author','Website','Actions'].map(x=><th key={x} style={th}>{x}</th>)}</tr></thead><tbody>{mods.length===0?<tr><td colSpan={7} style={{...td,color:'#64748b'}}>{busy?'Reading inventory…':view==='active'?'No active mods found.':'No quarantined mods.'}</td></tr>:mods.map(mod=><tr key={mod.folder} style={{background:selected.has(mod.folder)?'rgba(99,102,241,.08)':'transparent'}}><td style={td}><input type="checkbox" aria-label={`Select ${mod.name}`} checked={selected.has(mod.folder)} onChange={()=>toggle(mod.folder)}/></td><td style={{...td,fontWeight:600,overflowWrap:'anywhere'}}>{mod.name}</td><td style={{...td,overflowWrap:'anywhere'}}><code>{mod.folder}</code></td><td style={td}>{mod.version||'—'}</td><td style={{...td,overflowWrap:'anywhere'}}>{mod.author||'—'}</td><td style={{...td,minWidth:0}}>{mod.website?<a href={/^https?:\/\//i.test(mod.website)?mod.website:undefined} target="_blank" rel="noreferrer" title={mod.website} style={{color:'#818cf8',display:'block',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{mod.website}</a>:'—'}</td><td style={td}><div style={{display:'flex',gap:6,flexWrap:'wrap'}}>{view==='active'?<><button disabled={busy} onClick={()=>action(mod,'MOD_QUARANTINE')} style={button('#b45309')}>Quarantine</button><button disabled={busy} onClick={()=>action(mod,'MOD_DELETE')} style={button('#991b1b')}>Delete</button></>:<button disabled={busy} onClick={()=>action(mod,'MOD_RESTORE')} style={button('#15803d')}>Restore</button>}</div></td></tr>)}</tbody></table></div><p style={{color:'#64748b',fontSize:'.78rem'}}>Quarantine moves mods into private agent storage. Restore returns them to Mods. Changes take effect after server restart.</p></div>;
}
function button(background:string){return{background,color:'white',border:0,borderRadius:5,padding:'.45rem .65rem',cursor:'pointer',flexShrink:0};}
