'use client';
import { useCallback, useEffect, useState } from 'react';
import { api, Job, PlayerRecord, ServerAdminRecord, ServerInstance } from '../../../lib/api';
import { getStoredOrgId } from '../../../lib/auth';

type JobResult={data?:{admins?:ServerAdminRecord[]};errorMessage?:string};
function duration(seconds:number){const h=Math.floor(seconds/3600),m=Math.floor((seconds%3600)/60);return h?`${h}h ${m}m`:`${m}m`;}

export default function PlayersPage(){
  const orgId=getStoredOrgId(); const [servers,setServers]=useState<ServerInstance[]>([]); const [serverId,setServerId]=useState('');
  const [players,setPlayers]=useState<PlayerRecord[]>([]); const [admins,setAdmins]=useState<ServerAdminRecord[]>([]); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
  useEffect(()=>{if(!orgId)return;api.get<ServerInstance[]>(`/api/orgs/${orgId}/server-instances`).then(s=>{setServers(s);if(s[0])setServerId(s[0].id);}).catch(e=>setError(e.message));},[orgId]);
  const waitForJob=useCallback(async(runId:string)=>{for(let i=0;i<30;i++){await new Promise(r=>setTimeout(r,1000));const jobs=await api.get<Job[]>(`/api/orgs/${orgId}/jobs?limit=100&serverInstanceId=${encodeURIComponent(serverId)}`);const job=jobs.find(j=>j.latestRun?.id===runId);if(job?.latestRun?.status==='failed')throw new Error((job.latestRun.result as JobResult)?.errorMessage||'Agent job failed');if(job?.latestRun?.status==='success')return(job.latestRun.result||{})as JobResult;}throw new Error('Agent job timed out');},[orgId,serverId]);
  const loadPlayers=useCallback(async()=>{if(!orgId||!serverId)return;try{setPlayers(await api.get<PlayerRecord[]>(`/api/orgs/${orgId}/players?serverInstanceId=${encodeURIComponent(serverId)}`));setError('');}catch(e){setError(e instanceof Error?e.message:'Failed to load players');}},[orgId,serverId]);
  const loadAdmins=useCallback(async()=>{if(!orgId||!serverId)return;try{const queued=await api.post<{jobRunId:string}>(`/api/orgs/${orgId}/jobs`,{serverInstanceId:serverId,type:'PLAYER_ADMIN_LIST',payload:{}});const result=await waitForJob(queued.jobRunId);setAdmins(result.data?.admins||[]);}catch(e){setError(e instanceof Error?e.message:'Failed to read serveradmin.xml');}},[orgId,serverId,waitForJob]);
  useEffect(()=>{void loadPlayers();const t=setInterval(()=>void loadPlayers(),5000);return()=>clearInterval(t);},[loadPlayers]);
  useEffect(()=>{if(serverId)void loadAdmins();},[serverId,loadAdmins]);
  async function moderationAction(player:PlayerRecord,type:'PLAYER_KICK'|'PLAYER_BAN'){
    if(!orgId)return;const identifier=player.steamId||(player.eosId?`EOS_${player.eosId}`:player.name);
    const reason=window.prompt(type==='PLAYER_KICK'?'Kick reason:':'Ban reason:',type==='PLAYER_KICK'?'Removed by administrator':'Banned by administrator');if(reason===null)return;
    const durationValue=type==='PLAYER_BAN'?window.prompt('Ban duration (examples: 1 days, 12 hours, 0 minutes for permanent):','1 days'):null;if(type==='PLAYER_BAN'&&durationValue===null)return;
    const platform=player.steamId?'Steam':player.eosId?'EOS':undefined;try{await api.post(`/api/orgs/${orgId}/jobs`,{serverInstanceId:serverId,type,payload:{identifier,platform,reason,...(durationValue?{duration:durationValue}:{})}});setMessage(`${type==='PLAYER_KICK'?'Kick':'Ban'} queued for ${player.name}.`);setError('');}catch(e){setError(e instanceof Error?e.message:'Command failed');}
  }
  async function kickAll(){
    if(!orgId||!serverId||busy)return;const reason=window.prompt('Reason shown to every kicked player:','Server maintenance');if(reason===null)return;if(!confirm(`Kick all ${players.filter(player=>player.online).length} online player(s)?`))return;
    setBusy(true);setError('');setMessage('');try{const queued=await api.post<{jobRunId:string}>(`/api/orgs/${orgId}/jobs`,{serverInstanceId:serverId,type:'PLAYER_KICK_ALL',payload:{reason}});await waitForJob(queued.jobRunId);await loadPlayers();setMessage('Kick all completed and verified: 0 players online.');}catch(e){setError(e instanceof Error?e.message:'Kick all failed');}finally{setBusy(false);}
  }
  function adminFor(player:PlayerRecord){const ids=[player.steamId,player.eosId,player.eosId?`EOS_${player.eosId}`:null].filter(Boolean).map(v=>String(v).toLowerCase());return admins.find(a=>ids.includes(a.userId.toLowerCase())||(!ids.length&&a.name?.toLowerCase()===player.name.toLowerCase()));}
  async function adminAction(player:PlayerRecord,promote:boolean){
    if(!orgId||busy)return;const identifier=player.steamId||(player.eosId?`EOS_${player.eosId}`:'');if(!identifier){setError('Steam or EOS ID required for admin changes.');return;}
    const verb=promote?'promote':'demote';if(!confirm(`${promote?'Promote':'Demote'} ${player.name} ${promote?'to':'from'} 7DTD administrator?`))return;
    const platform=player.steamId?'Steam':'EOS';setBusy(true);setError('');setMessage('');try{const queued=await api.post<{jobRunId:string}>(`/api/orgs/${orgId}/jobs`,{serverInstanceId:serverId,type:promote?'PLAYER_ADMIN_PROMOTE':'PLAYER_ADMIN_DEMOTE',payload:{platform,identifier}});await waitForJob(queued.jobRunId);await loadAdmins();setMessage(`${player.name} ${verb}d successfully. serveradmin.xml refreshed.`);}catch(e){setError(e instanceof Error?e.message:`Failed to ${verb} player`);}finally{setBusy(false);}
  }
  const th={padding:'.65rem',textAlign:'left' as const,color:'#64748b',fontSize:'.72rem',borderBottom:'1px solid #252532'};const td={padding:'.7rem',color:'#cbd5e1',fontSize:'.82rem',borderBottom:'1px solid #1a1a24'};
  return <div style={{maxWidth:'100%',minWidth:0}}><div style={{display:'flex',justifyContent:'space-between',gap:12,marginBottom:'1.25rem'}}><div><h1 style={{margin:0,color:'#f1f5f9',fontSize:'1.5rem'}}>Players</h1><p style={{color:'#64748b',margin:'.25rem 0 0'}}>Live presence from <code>lp</code>; administrator state from <code>serveradmin.xml</code></p></div><div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap'}}><button disabled={busy||!serverId} onClick={()=>void kickAll()} style={button('#991b1b')}>Kick all</button><button disabled={busy||!serverId} onClick={()=>void loadAdmins()} style={button('#334155')}>Refresh admins</button><select value={serverId} onChange={e=>setServerId(e.target.value)} style={{background:'#111118',color:'#e2e8f0',border:'1px solid #252532',borderRadius:6,padding:'.5rem'}}>{servers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div></div>
  {error&&<div style={{color:'#f87171',marginBottom:10}}>{error}</div>}{message&&<div style={{color:'#4ade80',marginBottom:10}}>{message}</div>}
  <div style={{background:'#111118',border:'1px solid #1e1e2a',borderRadius:9,overflowX:'auto'}}><table style={{width:'100%',minWidth:1050,borderCollapse:'collapse'}}><thead><tr>{['Status','Name','Steam / EOS ID','Admin','Entity','Session','Lifetime','Last Seen','Actions'].map(x=><th key={x} style={th}>{x}</th>)}</tr></thead><tbody>{players.length===0?<tr><td colSpan={9} style={{...td,color:'#64748b'}}>No players discovered yet. Records appear after server logs or an <code>lp</code> poll identify them.</td></tr>:players.map(p=>{const admin=adminFor(p);return <tr key={p.id}><td style={td}><span style={{color:p.online?'#4ade80':'#64748b'}}>{p.online?'● Online':'○ Offline'}</span></td><td style={{...td,fontWeight:600}}>{p.name}</td><td style={td}><code>{p.steamId||p.eosId||'—'}</code><div style={{color:'#475569',fontSize:'.68rem'}}>{p.steamId?'Steam':p.eosId?'EOS':'Name fallback'}</div></td><td style={td}>{admin?<span style={{color:'#fbbf24'}}>Admin (level {admin.permissionLevel})</span>:<span style={{color:'#64748b'}}>Player</span>}</td><td style={td}>{p.entityId??'—'}</td><td style={td}>{duration(p.sessionSeconds)}</td><td style={td}>{duration(p.lifetimeSeconds)}</td><td style={td}>{new Date(p.lastSeenAt).toLocaleString()}</td><td style={td}><div style={{display:'flex',gap:6,flexWrap:'wrap'}}><button disabled={!p.online||busy} onClick={()=>moderationAction(p,'PLAYER_KICK')} style={button('#b45309')}>Kick</button><button disabled={busy} onClick={()=>moderationAction(p,'PLAYER_BAN')} style={button('#991b1b')}>Ban</button>{admin?<button disabled={busy} onClick={()=>adminAction(p,false)} style={button('#7c2d12')}>Demote</button>:<button disabled={busy||(!p.steamId&&!p.eosId)} onClick={()=>adminAction(p,true)} style={button('#15803d')}>Promote</button>}</div></td></tr>})}</tbody></table></div></div>;
}
function button(background:string){return{background,color:'white',border:0,borderRadius:5,padding:'.35rem .55rem',cursor:'pointer',whiteSpace:'nowrap' as const};}
