'use client';
import React,{useCallback,useEffect,useState} from 'react';
import { useParams } from 'next/navigation';
import { api, Host, Job, ServerInstance } from '../../../../lib/api';
import { getStoredOrgId } from '../../../../lib/auth';

const card:React.CSSProperties={background:'#111118',border:'1px solid #1e1e2a',borderRadius:10,padding:'1.25rem'};const td:React.CSSProperties={padding:'.7rem .8rem',borderBottom:'1px solid #1a1a24',color:'#cbd5e1',fontSize:'.82rem'};const th:React.CSSProperties={...td,color:'#64748b',fontSize:'.7rem',textAlign:'left',background:'#0d0d14'};
function duration(job:Job){const start=job.latestRun?.startedAt;if(!start)return'—';const end=job.latestRun?.finishedAt?new Date(job.latestRun.finishedAt).getTime():Date.now();return`${Math.max(0,Math.round((end-new Date(start).getTime())/1000))}s`;}
function resultText(job:Job){const r=job.latestRun?.result as {output?:string;errorMessage?:string}|null;return r?.errorMessage||r?.output||'';}

export default function ServerPage(){
  const {id}=useParams<{id:string}>();const orgId=getStoredOrgId();const [server,setServer]=useState<ServerInstance|null>(null);const [host,setHost]=useState<Host|null>(null);const [jobs,setJobs]=useState<Job[]>([]);const [tab,setTab]=useState<'overview'|'manage'|'jobs'>('overview');const [command,setCommand]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{if(!orgId||!id)return;try{const [s,h,j]=await Promise.all([api.get<ServerInstance>(`/api/orgs/${orgId}/server-instances/${id}`),api.get<Host[]>(`/api/orgs/${orgId}/hosts`),api.get<Job[]>(`/api/orgs/${orgId}/jobs?serverInstanceId=${encodeURIComponent(id)}&limit=50`)]);setServer(s);setHost(h.find(x=>x.id===s.hostId)||null);setJobs(j);setMessage('');}catch(e){setMessage(e instanceof Error?e.message:'Failed to load server');}},[orgId,id]);
  useEffect(()=>{void load();const timer=setInterval(()=>void load(),5000);return()=>clearInterval(timer);},[load]);
  async function run(type:string,payload:Record<string,unknown>={}){if(!orgId||!server)return;setBusy(true);setMessage(type==='SERVER_KILL'?'Killing server process…':'');try{const queued=await api.post<{jobRunId:string}>(`/api/orgs/${orgId}/jobs`,{serverInstanceId:server.id,type,payload});if(type==='SERVER_KILL'){for(let attempt=0;attempt<30;attempt++){await new Promise(resolve=>setTimeout(resolve,500));const rows=await api.get<Job[]>(`/api/orgs/${orgId}/jobs?serverInstanceId=${encodeURIComponent(server.id)}&limit=50`);const job=rows.find(row=>row.latestRun?.id===queued.jobRunId);if(job?.latestRun?.status==='failed')throw new Error(resultText(job)||'Kill job failed');if(job?.latestRun?.status==='success'){setJobs(rows);setHost(current=>current?{...current,lastMetrics:{...(current.lastMetrics||{}),gameReachable:false}}:current);setMessage('Kill verified: 7DTD process terminated and server is offline.');return;}}throw new Error('Kill job timed out');}setMessage(`${type} requested.`);setTab('jobs');setTimeout(()=>void load(),1000);}catch(e){setMessage(e instanceof Error?e.message:'Job failed');}finally{setBusy(false);}}
  function kickAll(){const reason=window.prompt('Reason shown to every kicked player:','Server maintenance');if(reason===null)return;if(confirm('Kick every player currently connected to this server?'))void run('PLAYER_KICK_ALL',{reason});}
  if(!server)return <div style={{color:message?'#f87171':'#64748b'}}>{message||'Loading server…'}</div>;
  const online=Boolean(host?.lastMetrics?.gameReachable);const tabs:[typeof tab,string][]=[['overview','Overview'],['manage','Manage'],['jobs','Recent jobs']];
  return <div><a href="/dashboard" style={{color:'#64748b',textDecoration:'none',fontSize:'.82rem'}}>‹ All servers</a><div style={{display:'flex',justifyContent:'space-between',alignItems:'start',margin:'1rem 0'}}><div><h1 style={{color:'#f1f5f9',margin:0,fontSize:'1.6rem'}}>{server.name}</h1><p style={{color:'#64748b',margin:'.3rem 0 0'}}>{server.gameType.toUpperCase()} on {host?.name||'unknown host'}</p></div><span style={{color:online?'#4ade80':'#f87171',fontWeight:600}}>{online?'● Online':'○ Offline'}</span></div>
    <div style={{display:'flex',gap:6,borderBottom:'1px solid #1e1e2a',marginBottom:'1rem'}}>{tabs.map(([key,label])=><button key={key} onClick={()=>setTab(key)} style={{background:'transparent',border:0,borderBottom:tab===key?'2px solid #6366f1':'2px solid transparent',color:tab===key?'#f1f5f9':'#64748b',padding:'.7rem 1rem',cursor:'pointer'}}>{label}</button>)}</div>
    <div style={{display:'flex',justifyContent:'flex-end',marginBottom:'1rem'}}><button disabled={busy} onClick={kickAll} style={button('#7f1d1d')}>Kick all players</button></div>
    {message&&<div style={{color:message.includes('requested')?'#4ade80':'#fbbf24',marginBottom:12}}>{message}</div>}
    {tab==='overview'&&<div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:'1rem'}}><div style={card}><small style={{color:'#64748b'}}>SERVER</small><p style={{color:'#e2e8f0'}}>Status: {online?'Online':'Offline'}</p><p style={{color:'#94a3b8'}}>Install path: <code>{server.installPath||'Not set'}</code></p><p style={{color:'#94a3b8'}}>Telnet: {server.telnetHost||'not set'}:{server.telnetPort||'—'}</p></div><div style={card}><small style={{color:'#64748b'}}>HOST</small><p style={{color:'#e2e8f0'}}>{host?.name||'Unknown'}</p><p style={{color:'#94a3b8'}}>Agent: {host?.agentVersion||'unknown'}</p><p style={{color:'#94a3b8'}}>Last heartbeat: {host?.lastHeartbeatAt?new Date(host.lastHeartbeatAt).toLocaleString():'Never'}</p></div></div>}
    {tab==='manage'&&<div style={card}><h2 style={{color:'#e2e8f0',marginTop:0,fontSize:'1rem'}}>Server controls</h2><div style={{display:'flex',gap:8,marginBottom:'1.25rem',flexWrap:'wrap'}}><button disabled={busy} onClick={()=>run('SERVER_START')} style={button('#15803d')}>Start</button><button disabled={busy} onClick={()=>run('SERVER_RESTART')} style={button('#b45309')}>Restart</button><button disabled={busy} onClick={()=>{if(confirm('Begin a 60-second warning, save and back up the world, kick all players, then restart?'))void run('SERVER_SAFE_RESTART',{retention_count:10});}} style={button('#0369a1')}>Safe restart</button><button disabled={busy} onClick={()=>run('SERVER_STOP')} style={button('#991b1b')}>Stop</button></div><label style={{color:'#94a3b8',fontSize:'.8rem'}}>Console command</label><div style={{display:'flex',gap:8,marginTop:6}}><input value={command} onChange={e=>setCommand(e.target.value)} placeholder="version or listplayers" style={{flex:1,background:'#0d0d14',border:'1px solid #252532',borderRadius:6,padding:'.6rem',color:'#e2e8f0'}}/><button disabled={busy||!command.trim()} onClick={()=>{void run('RCON',{command:command.trim()});setCommand('');}} style={button('#4f46e5')}>Send</button></div><div style={{display:'flex',gap:12,marginTop:'1.5rem',flexWrap:'wrap'}}><a href="/players" style={{color:'#818cf8'}}>Players</a><a href="/mods" style={{color:'#818cf8'}}>Mods</a><a href="/saves" style={{color:'#818cf8'}}>Saves</a><a href="/logs" style={{color:'#818cf8'}}>Logs</a><a href="/health" style={{color:'#818cf8'}}>Health</a></div><div style={{marginTop:'2rem',paddingTop:'1.25rem',borderTop:'1px solid #3f1d25'}}><h3 style={{color:'#f87171',fontSize:'.9rem',margin:'0 0 .4rem'}}>Danger zone</h3><p style={{color:'#fca5a5',fontSize:'.8rem'}}><strong>Kill process:</strong> immediately terminates 7DTD without saving. This can corrupt world or player data. Use only when normal Stop fails.</p><button disabled={busy} onClick={()=>{if(confirm('WARNING: This immediately kills 7DTD without saving and can corrupt world or player data.\n\nKill the server process now?'))void run('SERVER_KILL');}} style={{...button('#dc2626'),marginBottom:'1rem'}}>Kill process</button><p style={{color:'#94a3b8',fontSize:'.8rem'}}>Wipe save stops the server, permanently deletes its configured world save, then starts a fresh world.</p><button disabled={busy} onClick={()=>{if(confirm('Are you Sure, This Cannot Be Undone'))void run('SERVER_WIPE_SAVE',{confirmed:true});}} style={button('#7f1d1d')}>Wipe save and restart</button></div></div>}
    {tab==='jobs'&&<div style={{...card,padding:0,overflow:'hidden'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['Type','Started by','Status','Created','Duration','Output'].map(x=><th key={x} style={th}>{x}</th>)}</tr></thead><tbody>{jobs.length===0?<tr><td colSpan={6} style={td}>No jobs for this server.</td></tr>:jobs.map(job=><tr key={job.id}><td style={td}><code>{job.type}</code></td><td style={td} title={job.startedBy?.email}>{job.startedBy?.name||'Unknown'}</td><td style={{...td,color:job.latestRun?.status==='success'?'#4ade80':job.latestRun?.status==='failed'?'#f87171':'#fbbf24'}}>{job.latestRun?.status||'pending'}</td><td style={td}>{new Date(job.createdAt).toLocaleString()}</td><td style={td}>{duration(job)}</td><td style={{...td,maxWidth:340,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}} title={resultText(job)}>{resultText(job)||'—'}</td></tr>)}</tbody></table></div>}
  </div>;
}
function button(background:string):React.CSSProperties{return{background,color:'white',border:0,borderRadius:6,padding:'.55rem .85rem',cursor:'pointer'};}
