'use client';
import {useCallback,useEffect,useState} from 'react';
import {api} from '../../../lib/api';
import {getStoredOrgId} from '../../../lib/auth';

type SecurityData={attemptsPerStage:number;mathChallengeEnabled:boolean;registrationIpQuotaEnabled:boolean;registrationIpLimit:number;recaptchaConfigured:boolean;recaptchaSiteKey:string;lockoutPolicy:{afterFailures:number;durationMinutes:number;label:string}[];accounts:{id:string;email:string;name:string|null;role:string;failedAttempts:number;lockoutLevel:number;blockedUntil:string|null;locked:boolean;attemptsRemaining:number}[]};
const card:React.CSSProperties={background:'#111118',border:'1px solid #1e1e2a',borderRadius:10,padding:'1.1rem'};
const input:React.CSSProperties={background:'#08080c',color:'#e2e8f0',border:'1px solid #252532',borderRadius:6,padding:'.6rem',width:'100%'};
const button=(color:string):React.CSSProperties=>({background:color,color:'white',border:0,borderRadius:6,padding:'.55rem .8rem',cursor:'pointer'});

export default function SecurityPage(){
 const orgId=getStoredOrgId(),[data,setData]=useState<SecurityData|null>(null),[siteKey,setSiteKey]=useState(''),[secretKey,setSecretKey]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const refresh=useCallback(async()=>{if(!orgId)return;const value=await api.get<SecurityData>(`/api/orgs/${orgId}/security`);setData(value);setSiteKey(value.recaptchaSiteKey||'');},[orgId]);
 useEffect(()=>{void refresh().catch(e=>setError(e instanceof Error?e.message:'Could not load security settings'));},[refresh]);
 async function save(event:React.FormEvent){event.preventDefault();if(!orgId)return;setBusy(true);setError('');setMessage('');try{await api.post(`/api/orgs/${orgId}/integrations/recaptcha`,{siteKey,secretKey:secretKey||undefined});setSecretKey('');await refresh();setMessage('reCAPTCHA enabled for dashboard sign-in.');}catch(e){setError(e instanceof Error?e.message:'Could not save reCAPTCHA');}finally{setBusy(false);}}
 async function clear(){if(!orgId||!confirm('Disable reCAPTCHA on dashboard sign-in? Escalating lockouts and math challenges remain enabled.'))return;setBusy(true);try{await api.delete(`/api/orgs/${orgId}/integrations/recaptcha`);setSiteKey('');setSecretKey('');await refresh();setMessage('reCAPTCHA disabled.');}catch(e){setError(e instanceof Error?e.message:'Could not disable reCAPTCHA');}finally{setBusy(false);}}
 return <div><h1 style={{margin:'0 0 .25rem',color:'#f1f5f9',fontSize:'1.5rem'}}>Security</h1><p style={{color:'#64748b',margin:'0 0 1.4rem'}}>Dashboard sign-in protection and account lockout visibility.</p>
 {error&&<div style={{color:'#f87171',marginBottom:10}}>{error}</div>}{message&&<div style={{color:'#4ade80',marginBottom:10}}>{message}</div>}
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10,marginBottom:'1rem'}}>{data?.lockoutPolicy.map((stage,index)=><div key={stage.label} style={card}><small style={{color:'#64748b'}}>STAGE {index+1}</small><div style={{color:'#e2e8f0',fontSize:'1.2rem',marginTop:6}}>3 failures → {stage.label}</div></div>)}</div>
 <div style={{...card,marginBottom:'1rem'}}><strong style={{color:'#e2e8f0'}}>Always-on protections</strong><ul style={{color:'#94a3b8',lineHeight:1.8,marginBottom:0}}><li>Every three failed attempts advances the account to the next lockout stage.</li><li>Only a successful login resets the stage back to five minutes.</li><li>A fresh server-signed math equation is required for every login attempt.</li><li>IP throttling remains active against distributed account probing.</li><li>Public registration is limited to {data?.registrationIpLimit??2} accounts per IP address. Administrators can still create accounts manually.</li></ul></div>
 <form onSubmit={save} style={{...card,marginBottom:'1rem'}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'start',marginBottom:12}}><div><strong style={{color:'#e2e8f0'}}>Google reCAPTCHA v2</strong><div style={{color:'#64748b',fontSize:'.78rem',marginTop:3}}>{data?.recaptchaConfigured?'Enabled — secret key stored encrypted':'Disabled until both keys are saved'}</div></div><span style={{color:data?.recaptchaConfigured?'#4ade80':'#fbbf24'}}>{data?.recaptchaConfigured?'● Active':'○ Inactive'}</span></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:10}}><label style={{color:'#94a3b8',fontSize:'.78rem'}}>Site key<input value={siteKey} onChange={e=>setSiteKey(e.target.value)} required style={{...input,marginTop:6}} placeholder="Public reCAPTCHA site key"/></label><label style={{color:'#94a3b8',fontSize:'.78rem'}}>Secret key<input type="password" value={secretKey} onChange={e=>setSecretKey(e.target.value)} style={{...input,marginTop:6}} placeholder={data?.recaptchaConfigured?'Leave blank to keep existing secret':'Private reCAPTCHA secret key'}/></label></div><div style={{display:'flex',gap:8,marginTop:12}}><button disabled={busy} style={button('#4f46e5')}>Save reCAPTCHA</button>{data?.recaptchaConfigured&&<button type="button" disabled={busy} onClick={()=>void clear()} style={button('#7f1d1d')}>Disable reCAPTCHA</button>}</div><p style={{color:'#64748b',fontSize:'.75rem',marginBottom:0}}>Create a reCAPTCHA v2 “I’m not a robot” site for your public hostname. Never place the secret key in the site-key field.</p></form>
 <div style={{...card,overflowX:'auto'}}><h2 style={{color:'#e2e8f0',fontSize:'1rem',marginTop:0}}>Account lockout status</h2><table style={{width:'100%',minWidth:720,borderCollapse:'collapse'}}><thead><tr>{['Account','Role','Failed attempts','Escalation','Status'].map(label=><th key={label} style={{textAlign:'left',padding:'.65rem',color:'#64748b',fontSize:'.72rem',borderBottom:'1px solid #252532'}}>{label}</th>)}</tr></thead><tbody>{data?.accounts.map(account=><tr key={account.id}><td style={td}>{account.name||account.email}<small style={{display:'block',color:'#64748b'}}>{account.email}</small></td><td style={td}>{account.role}</td><td style={td}>{account.failedAttempts}/3 ({account.attemptsRemaining} remaining)</td><td style={td}>{account.locked?`Stage ${Math.max(1,account.lockoutLevel)}`:`Next: Stage ${Math.min(4,account.lockoutLevel+1)}`}</td><td style={{...td,color:account.locked?'#f87171':'#4ade80'}}>{account.locked&&account.blockedUntil?`Locked until ${new Date(account.blockedUntil).toLocaleString()}`:'Available'}</td></tr>)}</tbody></table></div>
 </div>;
}
const td:React.CSSProperties={padding:'.7rem',color:'#cbd5e1',fontSize:'.82rem',borderBottom:'1px solid #1a1a24'};
