'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {api,ChatMessage,Job,ServerInstance} from '../../../lib/api';
import {getStoredOrgId} from '../../../lib/auth';

export default function ChatPage(){
 const orgId=getStoredOrgId();const [servers,setServers]=useState<ServerInstance[]>([]);const [serverId,setServerId]=useState('');const [messages,setMessages]=useState<ChatMessage[]>([]);const [enabled,setEnabled]=useState(false);const [webhookUrl,setWebhookUrl]=useState('');const [saving,setSaving]=useState(false);const [reply,setReply]=useState('');const [sending,setSending]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const bottom=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!orgId)return;api.get<ServerInstance[]>(`/api/orgs/${orgId}/server-instances`).then(rows=>{const game=rows.filter(row=>row.gameType==='7dtd');setServers(game);if(game[0])setServerId(game[0].id);}).catch(e=>setError(e.message));},[orgId]);
 const load=useCallback(async()=>{if(!orgId||!serverId)return;try{setMessages(await api.get<ChatMessage[]>(`/api/orgs/${orgId}/chat?serverInstanceId=${encodeURIComponent(serverId)}&limit=300`));setError('');}catch(e){setError(e instanceof Error?e.message:'Failed to load chat');}},[orgId,serverId]);
 useEffect(()=>{if(!orgId||!serverId)return;api.get<{enabled:boolean;webhookUrl:string}>(`/api/orgs/${orgId}/chat/settings?serverInstanceId=${encodeURIComponent(serverId)}`).then(s=>{setEnabled(s.enabled);setWebhookUrl(s.webhookUrl);}).catch(e=>setError(e.message));void load();const timer=setInterval(()=>void load(),3000);return()=>clearInterval(timer);},[orgId,serverId,load]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:'auto'});},[messages]);
 async function save(){if(!orgId||!serverId)return;setSaving(true);setNotice('');try{await api.post(`/api/orgs/${orgId}/chat/settings`,{serverInstanceId:serverId,enabled,webhookUrl});setNotice('Chat relay settings saved.');setError('');}catch(e){setError(e instanceof Error?e.message:'Failed to save relay');}finally{setSaving(false);}}
 async function sendReply(e:React.FormEvent){e.preventDefault();const text=reply.trim();if(!orgId||!serverId||!text||sending)return;setSending(true);setNotice('');setError('');try{const escaped=text.replace(/\\/g,'\\\\').replace(/"/g,'\\"');const queued=await withTimeout(api.post<{jobRunId:string}>(`/api/orgs/${orgId}/jobs`,{serverInstanceId:serverId,type:'RCON',payload:{command:`say "${escaped}"`}}),10000,'Server message request timed out before it was queued');let done:Job|undefined;for(let i=0;i<60;i++){const jobs=await withTimeout(api.get<Job[]>(`/api/orgs/${orgId}/jobs?limit=30&serverInstanceId=${encodeURIComponent(serverId)}`),5000,'Unable to read message job status');done=jobs.find(job=>job.latestRun?.id===queued.jobRunId);if(done?.latestRun?.status==='success'||done?.latestRun?.status==='failed')break;await new Promise(resolve=>setTimeout(resolve,250));}if(done?.latestRun?.status!=='success'){const result=done?.latestRun?.result as {errorMessage?:string}|undefined;throw new Error(result?.errorMessage||'Server message did not complete within 15 seconds');}setReply('');setNotice('Server message sent.');}catch(e){setError(e instanceof Error?e.message:'Failed to send server message');}finally{setSending(false);}}
 return <div><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'start',flexWrap:'wrap',marginBottom:'1rem'}}><div><h1 style={{margin:0,color:'#f1f5f9',fontSize:'1.5rem'}}>Player Chat</h1><p style={{color:'#64748b',margin:'.25rem 0 0'}}>Player-sent messages parsed from 7DTD logs. Server and console announcements are excluded.</p></div><select value={serverId} onChange={e=>setServerId(e.target.value)} style={input}>{servers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div>
 {error&&<div style={{color:'#f87171',marginBottom:10}}>{error}</div>}{notice&&<div style={{color:'#4ade80',marginBottom:10}}>{notice}</div>}
 <div style={{background:'#111118',border:'1px solid #252532',borderRadius:9,padding:'1rem',marginBottom:'1rem'}}><strong style={{color:'#e2e8f0'}}>Discord chat relay</strong><div style={{display:'flex',gap:8,alignItems:'center',marginTop:'.7rem',flexWrap:'wrap'}}><label style={{color:'#94a3b8',display:'flex',gap:6,alignItems:'center'}}><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/> Enabled</label><input type="url" value={webhookUrl} onChange={e=>setWebhookUrl(e.target.value)} placeholder="https://discord.com/api/webhooks/…" style={{...input,flex:1,minWidth:240}}/><button disabled={saving} onClick={save} style={button}>{saving?'Saving…':'Save relay'}</button></div><small style={{color:'#64748b'}}>Only new player messages are relayed. Discord mentions are neutralized to prevent unwanted pings.</small></div>
 <div style={{height:'calc(100vh - 430px)',minHeight:320,overflowY:'auto',background:'#08080c',border:'1px solid #1e1e2a',borderRadius:'9px 9px 0 0',padding:'1rem'}}>{messages.length===0?<div style={{color:'#64748b'}}>No player chat recorded yet.</div>:messages.map(row=><div key={row.id} style={{display:'grid',gridTemplateColumns:'150px minmax(100px,180px) 1fr',gap:10,padding:'.45rem 0',borderBottom:'1px solid #15151d',alignItems:'start'}}><time style={{color:'#475569',fontSize:'.75rem'}}>{new Date(row.createdAt).toLocaleString()}</time><strong style={{color:'#818cf8',overflowWrap:'anywhere'}}>{row.payload.playerName}</strong><div style={{color:'#cbd5e1',whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{row.payload.message}<small style={{color:'#475569',marginLeft:8}}>{row.payload.channel}</small></div></div>)}<div ref={bottom}/></div><form onSubmit={sendReply} style={{display:'flex',gap:8,background:'#111118',border:'1px solid #252532',borderTop:0,borderRadius:'0 0 9px 9px',padding:'.75rem'}}><span style={{color:'#64748b',alignSelf:'center',fontFamily:'monospace'}}>say</span><input value={reply} onChange={e=>setReply(e.target.value.replace(/[\r\n]/g,''))} maxLength={400} disabled={!serverId||sending} placeholder="Message players as Server…" aria-label="Server chat message" style={{...input,flex:1,minWidth:0}}/><button disabled={!serverId||!reply.trim()||sending} style={button}>{sending?'Sending…':'Send as Server'}</button></form></div>;
}
const input={background:'#0d0d14',color:'#e2e8f0',border:'1px solid #252532',borderRadius:6,padding:'.55rem .7rem'};const button={background:'#4f46e5',color:'white',border:0,borderRadius:6,padding:'.55rem .9rem',cursor:'pointer'};
function withTimeout<T>(promise:Promise<T>,milliseconds:number,message:string):Promise<T>{return Promise.race([promise,new Promise<T>((_,reject)=>setTimeout(()=>reject(new Error(message)),milliseconds))]);}
