'use client';
import { useCallback, useEffect, useState } from 'react';
import { api, Job, SaveRecord, Schedule, ServerInstance } from '../../../lib/api';
import { getStoredOrgId } from '../../../lib/auth';

type SaveJobResult={data?:{saves?:SaveRecord[];save?:SaveRecord};errorMessage?:string;output?:string};

export default function SavesPage(){
  const orgId=getStoredOrgId();
  const [servers,setServers]=useState<ServerInstance[]>([]);const [serverId,setServerId]=useState('');const [saves,setSaves]=useState<SaveRecord[]>([]);
  const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
  const [retention,setRetention]=useState(10);const [intervalMinutes,setIntervalMinutes]=useState(0);const [schedule,setSchedule]=useState<Schedule|null>(null);

  useEffect(()=>{if(!orgId)return;api.get<ServerInstance[]>(`/api/orgs/${orgId}/server-instances`).then(rows=>{const gameServers=rows.filter(row=>row.gameType==='7dtd');setServers(gameServers);if(gameServers[0])setServerId(gameServers[0].id);}).catch(e=>setError(e.message));},[orgId]);

  const waitForJob=useCallback(async(runId:string)=>{for(let i=0;i<180;i++){await new Promise(resolve=>setTimeout(resolve,1000));const jobs=await api.get<Job[]>(`/api/orgs/${orgId}/jobs?limit=100&serverInstanceId=${encodeURIComponent(serverId)}`);const job=jobs.find(row=>row.latestRun?.id===runId);if(job?.latestRun?.status==='failed'){const result=job.latestRun.result as SaveJobResult|undefined;throw new Error(result?.errorMessage||'Save operation failed');}if(job?.latestRun?.status==='success')return(job.latestRun.result||{})as SaveJobResult;}throw new Error('Save operation timed out');},[orgId,serverId]);

  const run=useCallback(async(type:string,payload:Record<string,unknown>={})=>{if(!orgId||!serverId)throw new Error('Select a server first');const queued=await api.post<{jobRunId:string}>(`/api/orgs/${orgId}/jobs`,{serverInstanceId:serverId,type,payload});return waitForJob(queued.jobRunId);},[orgId,serverId,waitForJob]);

  const refresh=useCallback(async()=>{if(!serverId)return;setError('');try{const result=await run('SAVE_LIST');setSaves(result.data?.saves||[]);}catch(e){setError(e instanceof Error?e.message:'Failed to list saves');}},[serverId,run]);
  useEffect(()=>{if(serverId)void refresh();},[serverId,refresh]);

  useEffect(()=>{if(!orgId||!serverId)return;api.get<Schedule[]>(`/api/orgs/${orgId}/schedules`).then(rows=>{const found=rows.find(row=>row.serverInstanceId===serverId&&row.jobType==='SAVE_BACKUP')||null;setSchedule(found);const payload=found?.payload||{};setRetention(Number(payload.retention_count)||10);setIntervalMinutes(found?.enabled?(Number(payload.interval_minutes)||cronToMinutes(found.cronExpression)):0);}).catch(e=>setError(e instanceof Error?e.message:'Failed to load backup schedule'));},[orgId,serverId]);

  async function backup(){setBusy(true);setError('');setMessage('Saving world and creating full backup…');try{const result=await run('SAVE_BACKUP',{retention_count:retention});setMessage(`Backup ${result.data?.save?.id||''} created.`);await refresh();}catch(e){setError(e instanceof Error?e.message:'Backup failed');setMessage('');}finally{setBusy(false);}}
  async function saveSettings(e:React.FormEvent){e.preventDefault();if(!orgId||!serverId)return;setBusy(true);setError('');setMessage('Saving backup policy…');try{const payload={retention_count:retention,interval_minutes:intervalMinutes};const body={name:'Automatic full-world backup',serverInstanceId:serverId,cronExpression:minutesToCron(intervalMinutes||60),jobType:'SAVE_BACKUP',payload,enabled:intervalMinutes>0};let saved:Schedule;if(schedule)saved=await api.patch<Schedule>(`/api/orgs/${orgId}/schedules/${schedule.id}`,body);else saved=await api.post<Schedule>(`/api/orgs/${orgId}/schedules`,body);setSchedule(saved);await run('SAVE_RETENTION',{retention_count:retention});await refresh();setMessage(intervalMinutes>0?`Backup policy saved. Next run ${saved.nextRunAt?new Date(saved.nextRunAt).toLocaleString():'is being scheduled'}.`:'Automatic backups disabled; retention saved.');}catch(err){setError(err instanceof Error?err.message:'Failed to save backup policy');setMessage('');}finally{setBusy(false);}}
  async function stopServer(){if(!confirm('Stop this server so a save can be restored?'))return;setBusy(true);setError('');setMessage('Stopping server…');try{await run('SERVER_STOP');setMessage('Server stopped. Restore is now permitted.');}catch(e){setError(e instanceof Error?e.message:'Stop failed');setMessage('');}finally{setBusy(false);}}
  async function restore(save:SaveRecord){const scope=save.kind==='full-world'?'the entire current world save':'the current Region directory';if(!confirm(`Restore ${save.id}?\n\nThis replaces ${scope}. The 7DTD server must already be stopped and will remain stopped.`))return;setBusy(true);setError('');setMessage('Restoring save…');try{await run('SAVE_RESTORE',{save_id:save.id,confirmed:true});setMessage(`${save.id} restored. Server remains stopped; start it after inspection.`);}catch(e){setError(e instanceof Error?e.message:'Restore failed');setMessage('');}finally{setBusy(false);}}
  async function remove(save:SaveRecord){if(!confirm(`Permanently delete backup ${save.id}?\n\nThis cannot be undone.`))return;setBusy(true);setError('');setMessage('');try{await run('SAVE_DELETE',{save_id:save.id,confirmed:true});setMessage(`${save.id} deleted.`);await refresh();}catch(e){setError(e instanceof Error?e.message:'Delete failed');}finally{setBusy(false);}}

  const button=(background:string)=>({background,color:'white',border:0,borderRadius:6,padding:'.5rem .75rem',cursor:busy?'wait':'pointer',whiteSpace:'nowrap' as const});
  return <div style={{maxWidth:'100%',minWidth:0}}>
    <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap',marginBottom:'1rem'}}><div><h1 style={{margin:0,color:'#f1f5f9',fontSize:'1.5rem'}}>World Saves</h1><p style={{color:'#64748b',margin:'.25rem 0 0'}}>Full backups and Region Healer snapshots</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button disabled={busy||!serverId} onClick={()=>void backup()} style={button('#15803d')}>Backup now</button><button disabled={busy||!serverId} onClick={()=>void stopServer()} style={button('#991b1b')}>Stop for restore</button><button disabled={busy||!serverId} onClick={()=>void refresh()} style={button('#334155')}>Refresh</button><select value={serverId} onChange={e=>setServerId(e.target.value)} style={{background:'#111118',color:'#e2e8f0',border:'1px solid #252532',borderRadius:6,padding:'.5rem'}}>{servers.map(server=><option key={server.id} value={server.id}>{server.name}</option>)}</select></div></div>
    <div style={{background:'#172033',border:'1px solid #334155',borderRadius:8,padding:'.75rem',color:'#94a3b8',fontSize:'.82rem',marginBottom:'1rem'}}>Restore never stops or starts 7DTD automatically. Stop it first. Full-world backups restore everything; Region Healer snapshots restore only region files. Region Healer is stopped during restore and remains off while the game is off.</div>
    {error&&<div style={{color:'#f87171',marginBottom:10}}>{error}</div>}{message&&<div style={{color:'#4ade80',marginBottom:10}}>{message}</div>}
    <form onSubmit={saveSettings} style={{background:'#111118',border:'1px solid #1e1e2a',borderRadius:9,padding:'1rem',display:'flex',gap:12,alignItems:'end',flexWrap:'wrap',marginBottom:'1rem'}}><label style={label}>Keep full backups<input type="number" min={1} max={100} value={retention} onChange={e=>setRetention(Math.max(1,Math.min(100,Number(e.target.value)||1)))} style={input}/></label><label style={label}>Automatic backup interval<select value={intervalMinutes} onChange={e=>setIntervalMinutes(Number(e.target.value))} style={input}><option value={0}>Disabled</option><option value={15}>Every 15 minutes</option><option value={30}>Every 30 minutes</option><option value={60}>Every 60 minutes</option><option value={120}>Every 120 minutes</option><option value={360}>Every 360 minutes</option><option value={720}>Every 720 minutes</option><option value={1440}>Every 1440 minutes</option></select></label><button disabled={busy||!serverId} style={button('#4f46e5')}>Save policy</button>{schedule?.enabled&&<span style={{color:'#64748b',fontSize:'.78rem',paddingBottom:'.55rem'}}>Next: {schedule.nextRunAt?new Date(schedule.nextRunAt).toLocaleString():'pending'}</span>}</form>
    <div style={{background:'#111118',border:'1px solid #1e1e2a',borderRadius:9,overflowX:'auto'}}><table style={{width:'100%',minWidth:760,borderCollapse:'collapse'}}><thead><tr>{['Backup','Type','Taken','Game day','Size','Actions'].map(label=><th key={label} style={{padding:'.7rem',textAlign:'left',color:'#64748b',fontSize:'.72rem',borderBottom:'1px solid #252532'}}>{label}</th>)}</tr></thead><tbody>{saves.length===0?<tr><td colSpan={6} style={{padding:'1rem',color:'#64748b'}}>No backups found.</td></tr>:saves.map(save=><tr key={save.id}><td style={td}><code>{save.id}</code></td><td style={td}><span style={{color:save.kind==='full-world'?'#4ade80':'#fbbf24'}}>{save.kind==='full-world'?'Full world':'Region Healer'}</span></td><td style={td}>{new Date(save.createdAt).toLocaleString()}</td><td style={td}>{save.gameDay>0?`Day ${save.gameDay}`:'Unknown'}</td><td style={td}>{formatBytes(save.sizeBytes)}</td><td style={td}><div style={{display:'flex',gap:6}}><button disabled={busy} onClick={()=>void restore(save)} style={button('#b45309')}>Restore</button><button disabled={busy} onClick={()=>void remove(save)} style={button('#7f1d1d')}>Delete</button></div></td></tr>)}</tbody></table></div>
    <p style={{color:'#64748b',fontSize:'.78rem'}}>Older Region Healer snapshots predate game-day metadata, so their day displays as Unknown. <a href="/region-healer" style={{color:'#818cf8'}}>Open Region Healer</a></p>
  </div>;
}

const td={padding:'.7rem',color:'#cbd5e1',fontSize:'.82rem',borderBottom:'1px solid #1a1a24'};
const label={display:'flex',flexDirection:'column' as const,gap:6,color:'#94a3b8',fontSize:'.78rem'};
const input={background:'#08080c',color:'#e2e8f0',border:'1px solid #252532',borderRadius:6,padding:'.55rem',minWidth:170};
function formatBytes(bytes:number){if(bytes<1024)return`${bytes} B`;if(bytes<1024*1024)return`${(bytes/1024).toFixed(1)} KB`;if(bytes<1024*1024*1024)return`${(bytes/1024/1024).toFixed(1)} MB`;return`${(bytes/1024/1024/1024).toFixed(2)} GB`;}
function minutesToCron(minutes:number){if(minutes<60)return`*/${minutes} * * * *`;if(minutes===60)return'0 * * * *';if(minutes<1440&&minutes%60===0)return`0 */${minutes/60} * * *`;return'0 0 * * *';}
function cronToMinutes(cron:string){const minuteStep=cron.match(/^\*\/(\d+) \* \* \* \*$/);if(minuteStep)return Number(minuteStep[1]);const hourStep=cron.match(/^0 \*\/(\d+) \* \* \*$/);if(hourStep)return Number(hourStep[1])*60;if(cron==='0 * * * *')return 60;if(cron==='0 0 * * *')return 1440;return 60;}
