'use client';

import { useRef,useState, type CSSProperties,type ReactNode } from 'react';

const miniButton:CSSProperties={background:'#252b3a',border:'1px solid #374151',borderRadius:4,color:'#cbd5e1',padding:'.3rem .5rem',cursor:'pointer',fontSize:'.72rem'};

export function ConfigEditor({focus,value,original,disabled,onChange,onSave}:{focus:boolean;value:string;original:string;disabled:boolean;onChange:(value:string)=>void;onSave:()=>void}){
 const [query,setQuery]=useState('');const [match,setMatch]=useState(0);const [wrap,setWrap]=useState(false);const areaRef=useRef<HTMLTextAreaElement|null>(null);const codeRef=useRef<HTMLDivElement|null>(null);const gutterRef=useRef<HTMLDivElement|null>(null);const lines=value.split('\n');const dirty=value!==original;
 function findNext(){if(!query)return;const start=Math.max(0,value.indexOf(query,match+1));const index=start>=0?start:value.indexOf(query);if(index<0)return;setMatch(index);const area=areaRef.current;if(area){area.focus();area.setSelectionRange(index,index+query.length);area.scrollTop=Math.max(0,(value.slice(0,index).split('\n').length-3)*20);}}
 return <section style={{display:'flex',flexDirection:'column',minHeight:focus?0:360,height:focus?'calc(100dvh - 11rem)':undefined,flex:focus?'1 1 auto':'1 1 360px',border:`1px solid ${dirty?'#6d28d9':'#303044'}`,borderRadius:8,overflow:'hidden',background:'#08090d',boxShadow:'0 12px 35px rgba(0,0,0,.25)'}}>
  <div style={{display:'flex',alignItems:'center',gap:8,padding:'.45rem .65rem',background:'#11131b',borderBottom:'1px solid #252938',flexWrap:'wrap'}}><span style={{color:dirty?'#fbbf24':'#4ade80',fontSize:'.7rem'}}>●</span><span style={{color:'#cbd5e1',fontFamily:'ui-monospace,monospace',fontSize:'.78rem'}}>config editor</span><span style={{color:'#475569',fontSize:'.72rem'}}>{lines.length} lines · {value.length.toLocaleString()} chars</span><span style={{flex:1}}/><span style={{display:'inline-flex',gap:7,alignItems:'center',color:'#64748b',fontSize:'.68rem',fontFamily:'ui-monospace,monospace'}}><i style={{color:'#93c5fd',fontStyle:'normal'}}>key</i><i style={{color:'#a7f3d0',fontStyle:'normal'}}>string</i><i style={{color:'#fbbf24',fontStyle:'normal'}}>number</i><i style={{color:'#c4b5fd',fontStyle:'normal'}}>bool</i></span><input aria-label="Find in config" value={query} onChange={e=>{setQuery(e.target.value);setMatch(0)}} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();findNext();}}} placeholder="Find…" style={{width:150,background:'#090b11',border:'1px solid #30384b',borderRadius:4,color:'#e2e8f0',padding:'.3rem .45rem',fontFamily:'ui-monospace,monospace',fontSize:'.75rem'}}/><button type="button" onClick={findNext} style={miniButton}>Find</button><button type="button" onClick={()=>setWrap(v=>!v)} style={miniButton}>{wrap?'No wrap':'Wrap'}</button></div>
  <div style={{display:'grid',gridTemplateColumns:'54px minmax(0,1fr)',flex:1,minHeight:focus?0:300}}><div ref={gutterRef} aria-hidden="true" style={{padding:'12px 10px 12px 0',textAlign:'right',color:'#475569',background:'#0c0e14',borderRight:'1px solid #1f2430',fontFamily:'ui-monospace,SFMono-Regular,Consolas,monospace',fontSize:13,lineHeight:'20px',userSelect:'none',overflow:'hidden'}}>{lines.map((_,index)=><div key={index}>{index+1}</div>)}</div><div style={{position:'relative',minWidth:0,background:'#08090d'}}><div ref={codeRef} aria-hidden="true" style={{position:'absolute',inset:0,overflow:'hidden',padding:12,whiteSpace:wrap?'pre-wrap':'pre',wordBreak:wrap?'break-word':'normal',fontFamily:'ui-monospace,SFMono-Regular,Consolas,monospace',fontSize:13,lineHeight:'20px',tabSize:2,color:'#dbe4f0'}}>{lines.map((line,index)=><div key={index} style={{minHeight:20}}>{highlightCodeLine(line,index)}</div>)}</div><textarea ref={areaRef} spellCheck={false} value={value} onChange={e=>onChange(e.target.value)} onScroll={e=>{if(codeRef.current){codeRef.current.scrollTop=e.currentTarget.scrollTop;codeRef.current.scrollLeft=e.currentTarget.scrollLeft;}if(gutterRef.current)gutterRef.current.scrollTop=e.currentTarget.scrollTop;}} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='s'){e.preventDefault();onSave();}if((e.ctrlKey||e.metaKey)&&e.key==='f'){e.preventDefault();setQuery('');}}} disabled={disabled} style={{position:'absolute',inset:0,width:'100%',height:'100%',minHeight:0,resize:'none',overflow:'auto',whiteSpace:wrap?'pre-wrap':'pre',wordBreak:wrap?'break-word':'normal',background:'transparent',border:0,outline:0,padding:12,color:'transparent',caretColor:'#f8fafc',fontFamily:'ui-monospace,SFMono-Regular,Consolas,monospace',fontSize:13,lineHeight:'20px',tabSize:2,WebkitTextFillColor:'transparent',zIndex:1}}/></div></div>
  <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',padding:'.35rem .65rem',background:'#11131b',borderTop:'1px solid #252938',color:'#64748b',fontSize:'.7rem',fontFamily:'ui-monospace,monospace'}}><span>{dirty?'Unsaved changes':'Saved'}{query&&value.toLowerCase().includes(query.toLowerCase())?' · match found':''}</span><span>UTF-8 · JSON/XML/text · Ctrl+S to save</span></div>
 </section>;
}

function highlightCodeLine(line:string,index:number){const token=/(#.*$|;.*$|\/\/.*$|<!--[\s\S]*?-->)|(<\/?[A-Za-z][^>]*>)|("(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*')|(\b(?:true|false|null|undefined|yes|no|on|off)\b)|(\b-?\d+(?:\.\d+)?\b)|([{}\[\]():=,])|([A-Za-z_][\w.-]*(?=\s*[:=]))/gi;const nodes:ReactNode[]=[];let last=0;let match:RegExpExecArray|null;while((match=token.exec(line))){if(match.index>last)nodes.push(<span key={`${index}-${last}`}>{line.slice(last,match.index)}</span>);const text=match[0];const color=match[1]?'#6b7280':match[2]?'#f472b6':match[3]?(new RegExp('\\s*[:=]').test(line.slice(match.index+text.length))?'#93c5fd':'#a7f3d0'):match[4]?'#c4b5fd':match[5]?'#fbbf24':match[6]?'#94a3b8':'#93c5fd';nodes.push(<span key={`${index}-${match.index}`} style={{color}}>{text}</span>);last=match.index+text.length;}if(last<line.length)nodes.push(<span key={`${index}-${last}`}>{line.slice(last)}</span>);return nodes.length?nodes:<span>&nbsp;</span>;}
